version:'3'  #(version of Docker compose)
services:
  mongodb  #(container name)
    image:mongo
      ports:
        - 27017:27017  #(HOST:CONTAINER)(port binding)
      environment:
        - MONGO-INITDB-ROOT_USERNAME=admin
        - MONGO-INITDB-ROOT_USERNAME=password
  mongo-express
    image:mongo-express
    ports:
      - 8080:8080
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo