version: '3.8'

services:
  reverse-proxy:
    image: innovatar/nginx_proxy
    hostname: nginx
    mem_limit: 128m 
    depends_on:
      - web
    ports:
      - 80:80
  web:
    image: innovatar/web
    hostname: web
    mem_limit: 128m 
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
